/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CarreirasRouteImport } from './routes/carreiras'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SociosJorgeRitzmannDeOliveiraRouteImport } from './routes/socios.jorge-ritzmann-de-oliveira'
import { Route as AreasDireitoMedicoRouteImport } from './routes/areas.direito-medico'
import { Route as PublicacoesNoticiasCvmAtualizacaoOfertasPublicasRouteImport } from './routes/publicacoes.noticias.cvm-atualizacao-ofertas-publicas'
import { Route as AtuacaoSegmentosInstituicoesFinanceirasRouteImport } from './routes/atuacao.segmentos.instituicoes-financeiras'
import { Route as AtuacaoSegmentosEmpresarialEstrategicoRouteImport } from './routes/atuacao.segmentos.empresarial-estrategico'
import { Route as AtuacaoSegmentosClientesCorporativosRouteImport } from './routes/atuacao.segmentos.clientes-corporativos'

const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreirasRoute = CarreirasRouteImport.update({
  id: '/carreiras',
  path: '/carreiras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SociosJorgeRitzmannDeOliveiraRoute =
  SociosJorgeRitzmannDeOliveiraRouteImport.update({
    id: '/socios/jorge-ritzmann-de-oliveira',
    path: '/socios/jorge-ritzmann-de-oliveira',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasDireitoMedicoRoute = AreasDireitoMedicoRouteImport.update({
  id: '/areas/direito-medico',
  path: '/areas/direito-medico',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacoesNoticiasCvmAtualizacaoOfertasPublicasRoute =
  PublicacoesNoticiasCvmAtualizacaoOfertasPublicasRouteImport.update({
    id: '/publicacoes/noticias/cvm-atualizacao-ofertas-publicas',
    path: '/publicacoes/noticias/cvm-atualizacao-ofertas-publicas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AtuacaoSegmentosInstituicoesFinanceirasRoute =
  AtuacaoSegmentosInstituicoesFinanceirasRouteImport.update({
    id: '/atuacao/segmentos/instituicoes-financeiras',
    path: '/atuacao/segmentos/instituicoes-financeiras',
    getParentRoute: () => rootRouteImport,
  } as any)
const AtuacaoSegmentosEmpresarialEstrategicoRoute =
  AtuacaoSegmentosEmpresarialEstrategicoRouteImport.update({
    id: '/atuacao/segmentos/empresarial-estrategico',
    path: '/atuacao/segmentos/empresarial-estrategico',
    getParentRoute: () => rootRouteImport,
  } as any)
const AtuacaoSegmentosClientesCorporativosRoute =
  AtuacaoSegmentosClientesCorporativosRouteImport.update({
    id: '/atuacao/segmentos/clientes-corporativos',
    path: '/atuacao/segmentos/clientes-corporativos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carreiras': typeof CarreirasRoute
  '/contato': typeof ContatoRoute
  '/areas/direito-medico': typeof AreasDireitoMedicoRoute
  '/socios/jorge-ritzmann-de-oliveira': typeof SociosJorgeRitzmannDeOliveiraRoute
  '/atuacao/segmentos/clientes-corporativos': typeof AtuacaoSegmentosClientesCorporativosRoute
  '/atuacao/segmentos/empresarial-estrategico': typeof AtuacaoSegmentosEmpresarialEstrategicoRoute
  '/atuacao/segmentos/instituicoes-financeiras': typeof AtuacaoSegmentosInstituicoesFinanceirasRoute
  '/publicacoes/noticias/cvm-atualizacao-ofertas-publicas': typeof PublicacoesNoticiasCvmAtualizacaoOfertasPublicasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carreiras': typeof CarreirasRoute
  '/contato': typeof ContatoRoute
  '/areas/direito-medico': typeof AreasDireitoMedicoRoute
  '/socios/jorge-ritzmann-de-oliveira': typeof SociosJorgeRitzmannDeOliveiraRoute
  '/atuacao/segmentos/clientes-corporativos': typeof AtuacaoSegmentosClientesCorporativosRoute
  '/atuacao/segmentos/empresarial-estrategico': typeof AtuacaoSegmentosEmpresarialEstrategicoRoute
  '/atuacao/segmentos/instituicoes-financeiras': typeof AtuacaoSegmentosInstituicoesFinanceirasRoute
  '/publicacoes/noticias/cvm-atualizacao-ofertas-publicas': typeof PublicacoesNoticiasCvmAtualizacaoOfertasPublicasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carreiras': typeof CarreirasRoute
  '/contato': typeof ContatoRoute
  '/areas/direito-medico': typeof AreasDireitoMedicoRoute
  '/socios/jorge-ritzmann-de-oliveira': typeof SociosJorgeRitzmannDeOliveiraRoute
  '/atuacao/segmentos/clientes-corporativos': typeof AtuacaoSegmentosClientesCorporativosRoute
  '/atuacao/segmentos/empresarial-estrategico': typeof AtuacaoSegmentosEmpresarialEstrategicoRoute
  '/atuacao/segmentos/instituicoes-financeiras': typeof AtuacaoSegmentosInstituicoesFinanceirasRoute
  '/publicacoes/noticias/cvm-atualizacao-ofertas-publicas': typeof PublicacoesNoticiasCvmAtualizacaoOfertasPublicasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carreiras'
    | '/contato'
    | '/areas/direito-medico'
    | '/socios/jorge-ritzmann-de-oliveira'
    | '/atuacao/segmentos/clientes-corporativos'
    | '/atuacao/segmentos/empresarial-estrategico'
    | '/atuacao/segmentos/instituicoes-financeiras'
    | '/publicacoes/noticias/cvm-atualizacao-ofertas-publicas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carreiras'
    | '/contato'
    | '/areas/direito-medico'
    | '/socios/jorge-ritzmann-de-oliveira'
    | '/atuacao/segmentos/clientes-corporativos'
    | '/atuacao/segmentos/empresarial-estrategico'
    | '/atuacao/segmentos/instituicoes-financeiras'
    | '/publicacoes/noticias/cvm-atualizacao-ofertas-publicas'
  id:
    | '__root__'
    | '/'
    | '/carreiras'
    | '/contato'
    | '/areas/direito-medico'
    | '/socios/jorge-ritzmann-de-oliveira'
    | '/atuacao/segmentos/clientes-corporativos'
    | '/atuacao/segmentos/empresarial-estrategico'
    | '/atuacao/segmentos/instituicoes-financeiras'
    | '/publicacoes/noticias/cvm-atualizacao-ofertas-publicas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarreirasRoute: typeof CarreirasRoute
  ContatoRoute: typeof ContatoRoute
  AreasDireitoMedicoRoute: typeof AreasDireitoMedicoRoute
  SociosJorgeRitzmannDeOliveiraRoute: typeof SociosJorgeRitzmannDeOliveiraRoute
  AtuacaoSegmentosClientesCorporativosRoute: typeof AtuacaoSegmentosClientesCorporativosRoute
  AtuacaoSegmentosEmpresarialEstrategicoRoute: typeof AtuacaoSegmentosEmpresarialEstrategicoRoute
  AtuacaoSegmentosInstituicoesFinanceirasRoute: typeof AtuacaoSegmentosInstituicoesFinanceirasRoute
  PublicacoesNoticiasCvmAtualizacaoOfertasPublicasRoute: typeof PublicacoesNoticiasCvmAtualizacaoOfertasPublicasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreiras': {
      id: '/carreiras'
      path: '/carreiras'
      fullPath: '/carreiras'
      preLoaderRoute: typeof CarreirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socios/jorge-ritzmann-de-oliveira': {
      id: '/socios/jorge-ritzmann-de-oliveira'
      path: '/socios/jorge-ritzmann-de-oliveira'
      fullPath: '/socios/jorge-ritzmann-de-oliveira'
      preLoaderRoute: typeof SociosJorgeRitzmannDeOliveiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/direito-medico': {
      id: '/areas/direito-medico'
      path: '/areas/direito-medico'
      fullPath: '/areas/direito-medico'
      preLoaderRoute: typeof AreasDireitoMedicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacoes/noticias/cvm-atualizacao-ofertas-publicas': {
      id: '/publicacoes/noticias/cvm-atualizacao-ofertas-publicas'
      path: '/publicacoes/noticias/cvm-atualizacao-ofertas-publicas'
      fullPath: '/publicacoes/noticias/cvm-atualizacao-ofertas-publicas'
      preLoaderRoute: typeof PublicacoesNoticiasCvmAtualizacaoOfertasPublicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atuacao/segmentos/instituicoes-financeiras': {
      id: '/atuacao/segmentos/instituicoes-financeiras'
      path: '/atuacao/segmentos/instituicoes-financeiras'
      fullPath: '/atuacao/segmentos/instituicoes-financeiras'
      preLoaderRoute: typeof AtuacaoSegmentosInstituicoesFinanceirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atuacao/segmentos/empresarial-estrategico': {
      id: '/atuacao/segmentos/empresarial-estrategico'
      path: '/atuacao/segmentos/empresarial-estrategico'
      fullPath: '/atuacao/segmentos/empresarial-estrategico'
      preLoaderRoute: typeof AtuacaoSegmentosEmpresarialEstrategicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atuacao/segmentos/clientes-corporativos': {
      id: '/atuacao/segmentos/clientes-corporativos'
      path: '/atuacao/segmentos/clientes-corporativos'
      fullPath: '/atuacao/segmentos/clientes-corporativos'
      preLoaderRoute: typeof AtuacaoSegmentosClientesCorporativosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarreirasRoute: CarreirasRoute,
  ContatoRoute: ContatoRoute,
  AreasDireitoMedicoRoute: AreasDireitoMedicoRoute,
  SociosJorgeRitzmannDeOliveiraRoute: SociosJorgeRitzmannDeOliveiraRoute,
  AtuacaoSegmentosClientesCorporativosRoute:
    AtuacaoSegmentosClientesCorporativosRoute,
  AtuacaoSegmentosEmpresarialEstrategicoRoute:
    AtuacaoSegmentosEmpresarialEstrategicoRoute,
  AtuacaoSegmentosInstituicoesFinanceirasRoute:
    AtuacaoSegmentosInstituicoesFinanceirasRoute,
  PublicacoesNoticiasCvmAtualizacaoOfertasPublicasRoute:
    PublicacoesNoticiasCvmAtualizacaoOfertasPublicasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
